Added functional test for deployment

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -64,5 +64,47 @@ jobs:
           LIGHTSAIL_SERVICE_NAME: "ashdavies-lightsail"
           LIGHTSAIL_REGION: "eu-west-2"
         run: |
-          PREVIOUS_DEPLOYMENT=$(aws lightsail get-container-service-deployments --service-name "$LIGHTSAIL_SERVICE_NAME" --region "$LIGHTSAIL_REGION" | jq '.deployments[0].containers')
-          aws lightsail create-container-service-deployment --service-name "$LIGHTSAIL_SERVICE_NAME" --region "$LIGHTSAIL_REGION" --containers "$PREVIOUS_DEPLOYMENT"
+          CONTAINERS=$(aws lightsail get-container-service-deployments \
+            --service-name "$LIGHTSAIL_SERVICE_NAME" \
+            --region "$LIGHTSAIL_REGION" | jq '.deployments[0].containers')
+
+          STATE=$(aws lightsail create-container-service-deployment \
+            --service-name "$LIGHTSAIL_SERVICE_NAME" \
+            --region "$LIGHTSAIL_REGION" \
+            --containers "$CONTAINERS" | jq '.nextDeployment.state')
+
+          TIMEOUT=$((SECONDS+300))
+
+          until [[
+            $STATE == 'ACTIVE'
+          ]]
+          do
+            REVISION_DETAILS=$(aws lightsail get-container-service-deployments \
+              --service-name "$LIGHTSAIL_SERVICE_NAME" \
+              --region "$LIGHTSAIL_REGION" | jq -r '.deployments[0]')
+
+            STATE=$(echo "$REVISION_DETAILS" | jq -r '.state');
+
+            echo "[i] Status: $STATE
+
+            if [[
+              $STATE == 'FAILED'
+            ]]
+            then
+              echo "[!] Deployment failed!"
+              exit 1
+            fi
+
+            # Safety condition to avoid unnecessary execution time
+            if [[ $SECONDS -gt $TIMEOUT ]]
+            then
+              echo "[!] Deployment failed to reach a steady state after 5 minutes" >&2
+              exit 1
+            fi
+
+            sleep 5
+          done
+
+          # Final output to evidence the state
+          echo "Deployment completed successfully!"
+          exit 0
